### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by pipermerriam** [nexusdev/dapple#125]
I get the following error when running `dapple test` in the dappsys repo.

```shell
$ dapple test
/Users/piper/.node/lib/node_modules/dapple/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /Users/piper/.node/lib/node_modules/dapple/node_modules/deasync/build/deasync.node
 → /Users/piper/.node/lib/node_modules/dapple/node_modules/deasync/build/Debug/deasync.node
 → /Users/piper/.node/lib/node_modules/dapple/node_modules/deasync/build/Release/deasync.node
 → /Users/piper/.node/lib/node_modules/dapple/node_modules/deasync/out/Debug/deasync.node
 → /Users/piper/.node/lib/node_modules/dapple/node_modules/deasync/Debug/deasync.node
 → /Users/piper/.node/lib/node_modules/dapple/node_modules/deasync/out/Release/deasync.node
 → /Users/piper/.node/lib/node_modules/dapple/node_modules/deasync/Release/deasync.node
 → /Users/piper/.node/lib/node_modules/dapple/node_modules/deasync/build/default/deasync.node
 → /Users/piper/.node/lib/node_modules/dapple/node_modules/deasync/compiled/5.4.1/darwin/x64/deasync.node
    at bindings (/Users/piper/.node/lib/node_modules/dapple/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/Users/piper/.node/lib/node_modules/dapple/node_modules/deasync/index.js:23:31)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/piper/.node/lib/node_modules/dapple/lib/vmtest.js:4:15)
    at Module._compile (module.js:397:26)
```

dapple was installed from master @ 4a543cbda69fc13f07e331028d19ef67602737cb using `npm install /path/to/dapple`.  I tried both a global install with `-g` and without.

Node and NPM versions.

```shell
$ npm --version
3.3.12
$ node --version
v5.4.1
```

**Comment by ryepdx** [comment]
Try deleting everything that comes up with `find -name "deasync.node"` and then running `npm rebuild`. Looks like it might be related to old output from node-gyp:
https://github.com/polotek/libxmljs/issues/253
https://github.com/tmpvar/jsdom/issues/757
https://github.com/arunoda/meteor-up/issues/309

**Comment by pipermerriam** [comment]
That fixed it.  Thanks.  For anyone else who has this issue, the `npm rebuild` command needs to be run from within the `node_modules/dapple` directory.
