### ISSUE TITLE
Error with lazreq when loading dapple as a dependency

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapple#147]
when including dapple as a dependency, I’ve get problems with lazreq: 
```
Error: Could not identify caller module
     at id_origin (node_modules/lazreq/js/lazreq.js:53:1)
     at lazreq (node_modules/lazreq/js/lazreq.js:74:1)
```

**Comment by mhhf** [comment]
cannot reproduce anymore, closing since its probably gone in v0.8
