### ISSUE TITLE
solidity JS compiler failover: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by jorisbontje** [nexusdev/dapple#159]
with dapple 0.3.0 on OSX
```
$ dapple build
Building...
/bin/sh: solc: command not found
No local solc found. Failing over to JS compiler...
/Users/mids/.node/lib/node_modules/dapple/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["rea

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Object.compile (/Users/mids/.node/lib/node_modules/dapple/node_modules/solc/index.js:13:34)
    at Function.buildSources (/Users/mids/.node/lib/node_modules/dapple/lib/build.js:75:29)
    at DestroyableTransform._flush (/Users/mids/.node/lib/node_modules/dapple/lib/streams/build.js:20:28)
    at DestroyableTransform.<anonymous> (/Users/mids/.node/lib/node_modules/dapple/node_modules/readable-stream/lib/_stream_transform.js:123:12)
    at DestroyableTransform.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7)
    at prefinish (/Users/mids/.node/lib/node_modules/dapple/node_modules/readable-stream/lib/_stream_writable.js:501:12)
    at finishMaybe (/Users/mids/.node/lib/node_modules/dapple/node_modules/readable-stream/lib/_stream_writable.js:509:7)
```

**Comment by defel** [comment]
Got the same error on OSX. When no native solc is installed. 

Testing the  https://github.com/nexusdev/feedbase.git

This is my json:  https://makerdao.slack.com/files/aweiher/F0UFBUZMG/-.js/edit

Problem occurs when running this line:  
```js
result = compileJSONMulti(JSON.stringify(input), optimise);
```

When this line is running (in the else-condition): 
```js
result = compileJSON(input, optimise);
````

everything works fine: 

```
dapple/feedbase❮git:master❯ ● » dapple test
Testing...
/bin/sh: solc: command not found
No local solc found. Failing over to JS compiler...

Summary
  Passed all 0 tests!
```

I am using `solc@0.3.0-1`.

**Comment by nmushegian** [comment]
https://github.com/nexusdev/dapple/pull/225
