### ISSUE TITLE
dapple test

### ISSUE THREAD

**Issue by cserb** [nexusdev/dapple#193]
```
Testing...
/bin/sh: solc: command not found
No local solc found. Failing over to JS compiler...
/usr/local/lib/node_modules/dapple/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSy

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Object.compile (/usr/local/lib/node_modules/dapple/node_modules/solc/index.js:13:34)
    at Function.buildSources (/usr/local/lib/node_modules/dapple/lib/build.js:75:29)
    at DestroyableTransform._flush (/usr/local/lib/node_modules/dapple/lib/streams/build.js:20:28)
    at DestroyableTransform.<anonymous> (/usr/local/lib/node_modules/dapple/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7)
    at prefinish (/usr/local/lib/node_modules/dapple/node_modules/readable-stream/lib/_stream_writable.js:465:12)
    at finishMaybe (/usr/local/lib/node_modules/dapple/node_modules/readable-stream/lib/_stream_writable.js:473:7)
```

**Comment by nmushegian** [comment]
Thanks!
Dupe:  https://github.com/nexusdev/dapple/issues/159
