### ISSUE TITLE
TypeError: _.object is not a function

### ISSUE THREAD

**Issue by nmushegian** [nexusdev/dapple#206]
```
(nexus) dev@83f5949d8f99:~/maker-core$ dapple test
Testing...
/home/dev/devenv/dapple/lib/workspace.js:59
    this.subDappfiles = _.object(_.map(this.sorted_dappfiles,
                          ^

TypeError: _.object is not a function
    at new Workspace (/home/dev/devenv/dapple/lib/workspace.js:59:27)
    at Function.atPackageRoot (/home/dev/devenv/dapple/lib/workspace.js:102:12)
    at Object.<anonymous> (/home/dev/devenv/dapple/cmd/main.js:160:29)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**Comment by nmushegian** [comment]
possibly related:  https://github.com/angular-ui/angular-google-maps/issues/1682

**Comment by nmushegian** [comment]
This is just in a devenv docker (whose state we probably screwed up somehow), works fine on my machine

**Comment by nmushegian** [comment]
looks like this is local to our setup

**Comment by ghuser** [comment]
Happens to me also:
package.json
```json
    {
      "name": "parser",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC",
      "dependencies": {
        "lodash": "^4.17.4"
      }
    }
```

```shell
    node -v 
    v7.6.0
```

parser.js
```js
    const _ = require('lodash');
    _.object(["key", "value"], ["a","b"]);
```

OS: ubuntu 16
