### ISSUE TITLE
Falls back to js solc even with local solc installed, then doesn't work

### ISSUE THREAD

**Issue by nmushegian** [nexusdev/dapple#208]
```
rune@mkbots:~/maker-core$ dapple test
Testing...
/usr/local/lib/node_modules/dapple/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSy

Error: Cannot find module 'memdown'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/dapple/node_modules/merkle-patricia-tree/baseTrie.js:3:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by nmushegian** [comment]
This happened on a fresh ubuntu image, but the latest dapple works fine on my local OSX. Already tried `npm cache clean`

**Comment by dbrock** [comment]
I never got the JavaScript `solc` to work either, for some reason (in fresh Ubuntu 15.10 environments).

**Comment by nmushegian** [comment]
reopen if problem persists after this:  https://github.com/nexusdev/dapple/pull/225
