### ISSUE TITLE
error on dapple test

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapple#217]
Has someone seen this before? Is this because i hit the gas limit?

```
Testing...
Using local solc installation...
/Users/mhhf/work/99_extern/nexus/dapple/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readF

Error: Assertion failed
    at assert (/Users/mhhf/work/99_extern/nexus/dapple/node_modules/ethereumjs-vm/node_modules/bn.js/lib/bn.js:6:21)
    at BN.iaddn (/Users/mhhf/work/99_extern/nexus/dapple/node_modules/ethereumjs-vm/node_modules/bn.js/lib/bn.js:2123:5)
    at BN.addn (/Users/mhhf/work/99_extern/nexus/dapple/node_modules/ethereumjs-vm/node_modules/bn.js/lib/bn.js:2191:25)
    at parseRunResult (/Users/mhhf/work/99_extern/nexus/dapple/node_modules/ethereumjs-vm/lib/runCall.js:147:40)
    at parseVmResults (/Users/mhhf/work/99_extern/nexus/dapple/node_modules/ethereumjs-vm/lib/runCode.js:236:7)
    at /Users/mhhf/work/99_extern/nexus/dapple/node_modules/async/lib/async.js:789:30
    at /Users/mhhf/work/99_extern/nexus/dapple/node_modules/async/lib/async.js:167:37
    at processImmediate [as _immediateCallback] (timers.js:383:17)
    at Function.module.exports.loopWhile (/Users/mhhf/work/99_extern/nexus/dapple/node_modules/deasync/index.js:64:21)
    at runTests (/Users/mhhf/work/99_extern/nexus/dapple/lib/streams/test.js:96:11)
``` 

Weird thing was: if i remove some tests - the error disappears, each removed test run successfully in isolation, also each test don't share any state.

**Comment by nmushegian** [comment]
I have not seen this before

**Comment by mhhf** [comment]
Closing since this cannot be reproduced and was maybe caused by a bug in a third party module which was resolved by now.
