### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by raineorshine** [nexusdev/dapple#246]
`dapple test` was working fine before I installed `solc` (when it was using the fallback compiler) but now I get this error:

```
$ dapple test
Testing...
Using local solc installation...
/Users/raine/.nvm/versions/node/v5.5.0/lib/node_modules/dapple/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Function.compile (/Users/raine/.nvm/versions/node/v5.5.0/lib/node_modules/dapple/lib/native_compiler.js:49:19)
    at Function.buildSources (/Users/raine/.nvm/versions/node/v5.5.0/lib/node_modules/dapple/lib/build.js:84:29)
    at DestroyableTransform._flush (/Users/raine/.nvm/versions/node/v5.5.0/lib/node_modules/dapple/lib/streams/build.js:20:28)
    at DestroyableTransform.<anonymous> (/Users/raine/.nvm/versions/node/v5.5.0/lib/node_modules/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7)
    at prefinish (/Users/raine/.nvm/versions/node/v5.5.0/lib/node_modules/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:465:12)
    at finishMaybe (/Users/raine/.nvm/versions/node/v5.5.0/lib/node_modules/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:473:7)
```

OSX 10.11.4
Node v5.5.0
Dapple v0.7.1
solc: 0.3.2-9e36bdda/Release-Darwin/appleclang/Interpreter

**Comment by mhhf** [comment]
This is very likely not a dapple problem. Do you have a working `solc`?
See this: https://github.com/ethereum/solidity/issues/490

**Comment by raineorshine** [comment]
Aha, you are right. I am getting the segfault in the issue you referenced.
