### ISSUE TITLE
 Error: Cannot find module 'vinyl'

### ISSUE THREAD

**Issue by jorisbontje** [nexusdev/dapple#249]
dapple installed with: `npm install -g dapple`

```
$ dapple build --template meteor --no-deploy-data

No configuration found! Generating...
? IPFS hostname: localhost
? IPFS port: 5001
? Ethereum JSON-RPC hostname: localhost
? Ethereum JSON-RPC port: 8545
? Default Ethereum account: 
Building...
module.js:327
   throw err;
   ^

Error: Cannot find module 'vinyl'
   at Function.Module._resolveFilename (module.js:325:15)
   at Function.Module._load (module.js:276:25)
   at Module.require (module.js:353:17)
   at Object.defineProperty.get [as File] (/usr/local/lib/node_modules/dapple/node_modules/lazreq/js/lazreq.js:58:42)
   at Function.atPackageRoot (/usr/local/lib/node_modules/dapple/lib/workspace.js:97:23)
   at Object.<anonymous> (/usr/local/lib/node_modules/dapple/cmd/main.js:101:29)
   at Module._compile (module.js:409:26)
   at Object.Module._extensions..js (module.js:416:10)
   at Module.load (module.js:343:32)
   at Function.Module._load (module.js:300:12)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! Maker-OTC@ build: `dapple build --template meteor --no-deploy-data`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Maker-OTC@ build script 'dapple build --template meteor --no-deploy-data'.
npm ERR! This is most likely a problem with the Maker-OTC package,
```

**Comment by mhhf** [comment]
Thanks for reporting. Should be fixed in the new master branch and will get included in the next version bump

**Comment by sunny-g** [comment]
@mhhf is this supposed to be fixed with version `0.7.2`? I'm still getting it when running `dapple test` with Node `v5.11.1` and NPM `v3.8.6`.

**Comment by mhhf** [comment]
Very weird... 
Should have been gone in 0.7.2...
Can you try this on your own machine and reopen this issue if you run into it again?
Also can you post the exact Error message?

**Comment by sunny-g** [comment]
@mhhf so it installed correctly locally (OSX 10.10.5, Node `v5.11.1`, NPM `3.8.6`), but now I'm getting a different error altogether (I also didn't specify an Ethereum account because I don't have one, not sure if related:)
```sh
$ ./node_modules/dapple/cmd/main.js test
No configuration found! Generating...
? IPFS hostname: localhost
? IPFS port: 5001
? Ethereum JSON-RPC hostname: localhost
? Ethereum JSON-RPC port: 8545
? Default Ethereum account:
Testing...
/Users/sunnygonnabathula/gitdev/whuffie-api/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["r

TypeError: Cannot read property 'ignore' of undefined
    at Workspace.getIgnoreGlobs (/Users/sunnygonnabathula/gitdev/whuffie-api/node_modules/dapple/lib/workspace.js:267:56)
    at getSourcePatterns (/Users/sunnygonnabathula/gitdev/whuffie-api/node_modules/dapple/lib/streams/package_stream.js:31:32)
    at DestroyableTransform._flush (/Users/sunnygonnabathula/gitdev/whuffie-api/node_modules/dapple/lib/streams/package_stream.js:47:20)
    at DestroyableTransform.<anonymous> (/Users/sunnygonnabathula/gitdev/whuffie-api/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7)
    at prefinish (/Users/sunnygonnabathula/gitdev/whuffie-api/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:465:12)
    at finishMaybe (/Users/sunnygonnabathula/gitdev/whuffie-api/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:473:7)
    at endWritable (/Users/sunnygonnabathula/gitdev/whuffie-api/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:485:3)
```

**Comment by mhhf** [comment]
Hopefully this should be gone now since the configuration is done differently
