### ISSUE TITLE
Global build fails

### ISSUE THREAD

**Issue by ameensol** [nexusdev/dapple#281]
I cloned the repo, cd into it, and then ran `npm i -g .`

Here's the error: 
```
/usr/local/lib/node_modules/dapple/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filena

ReferenceError: ethUtil is not defined
    at Blockchain.setGasLimit (/usr/local/lib/node_modules/dapple/node_modules/ethersim/lib/blockchain.js:138:16)
    at Object.module.exports.EVM (/usr/local/lib/node_modules/dapple/lib/web3Factory.js:65:33)
    at Object.TestPipeline (/usr/local/lib/node_modules/dapple/lib/pipelines.js:116:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/dapple/cmd/main.js:250:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
```
Any ideas?

**Comment by ameensol** [comment]
I tried to uninstall `npm r -g .` and reinstall from npm `npm i -g dapple` but now I'm getting the same error.

**Comment by ameensol** [comment]
Is there any chance this is a problem with `ethersim` or `ethereumJS`?

**Comment by nmushegian** [comment]
could be our ethersim fork, @mhhf is our man

**Comment by XertroV** [comment]
I've submitted a PR to EtherSim: https://github.com/iurimatias/EtherSim/pull/14/files

**Comment by ameensol** [comment]
Thanks, I appreciate it.

**Comment by mhhf** [comment]
Sry for the late reply.
We work on top of a custom ethersim fork: https://github.com/nexusdev/EtherSim.git
Should be resolved now!
