### ISSUE TITLE
dapple build => SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by jorisbontje** [nexusdev/dapple#284]
Trying to build `token-auction` with dapple 0.7.2 and node 6.3.1:

```
$ dapple build
Building...
Using local solc installation...
/Users/mids/.node/lib/node_modules/dapple/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"]

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Function.compile (/Users/mids/.node/lib/node_modules/dapple/lib/native_compiler.js:49:19)
    at Function.buildSources (/Users/mids/.node/lib/node_modules/dapple/lib/build.js:85:29)
    at DestroyableTransform._flush (/Users/mids/.node/lib/node_modules/dapple/lib/streams/build.js:20:28)
    at DestroyableTransform.<anonymous> (/Users/mids/.node/lib/node_modules/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at prefinish (/Users/mids/.node/lib/node_modules/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:465:12)
    at finishMaybe (/Users/mids/.node/lib/node_modules/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:473:7)
```

**Comment by jorisbontje** [comment]
Looks like that doing a `brew update` caused one of the `solc` dependencies to be removed. Running `solc` directly exposed the actual issue:

```
 solc contract.sol
dyld: lazy symbol binding failed: Symbol not found: __ZN4Json5ValueaSERKS0_
  Referenced from: /usr/local/lib/libsolidity.dylib
  Expected in: /usr/local/lib/libjsoncpp.dylib

dyld: Symbol not found: __ZN4Json5ValueaSERKS0_
  Referenced from: /usr/local/lib/libsolidity.dylib
  Expected in: /usr/local/lib/libjsoncpp.dylib

Trace/BPT trap: 5
```

**Comment by mhhf** [comment]
Would still be nice to forward and print out the error in case something went wrong.

**Comment by mhhf** [comment]
hmm, stderr of the subprocess is already forwarded and printed out. node doesn't seem to catch this error -.-
