### ISSUE TITLE
`dapple test` fails when run in submodule which doesn't have .dapple/.gitignore

### ISSUE THREAD

**Issue by nmushegian** [nexusdev/dapple#335]
```
~/maker-core/.dapple/packages/ds-token/dapple_packages/ds-auth# dapple test
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/root/maker-core/.dapple/packages/ds-token/dapple_packages/ds-auth/.dapple/.gitignore'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at State.initLocalDb (/usr/local/lib/node_modules/dapple/node_modules/dapple-core/state.js:72:10)
    at nextTask (/usr/local/lib/node_modules/dapple/node_modules/async/dist/async.js:5190:18)
    at /usr/local/lib/node_modules/dapple/node_modules/async/dist/async.js:5184:17
    at apply (/usr/local/lib/node_modules/dapple/node_modules/async/dist/async.js:41:29)
    at /usr/local/lib/node_modules/dapple/node_modules/async/dist/async.js:76:16
    at /usr/local/lib/node_modules/dapple/node_modules/async/dist/async.js:981:20
```
```
touch .dapple/.gitignore
dapple test
```
fixes it

**Comment by mhhf** [comment]
This was caused because of a race condition of creating the .dapple dir and the .gitignore file. Should be resolved solved in dapple 0.8.14. If someone runs into it again, please reopen.
