### ISSUE TITLE
TypeError: Cannot read property 'pop' of undefined

### ISSUE THREAD

**Issue by jorisbontje** [nexusdev/dapple#337]
with dapple 0.8.9 after running `dapple test`

```
/Users/mids/.node/lib/node_modules/dapple/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"]

TypeError: Cannot read property 'pop' of undefined
    at SecureTrie.Trie._updateNode (/Users/mids/.node/lib/node_modules/dapple/node_modules/merkle-patricia-tree/baseTrie.js:359:23)
    at /Users/mids/.node/lib/node_modules/dapple/node_modules/merkle-patricia-tree/baseTrie.js:106:16
    at /Users/mids/.node/lib/node_modules/dapple/node_modules/merkle-patricia-tree/baseTrie.js:442:14
    at processNode (/Users/mids/.node/lib/node_modules/dapple/node_modules/merkle-patricia-tree/baseTrie.js:447:23)
    at /Users/mids/.node/lib/node_modules/dapple/node_modules/merkle-patricia-tree/baseTrie.js:485:11
    at /Users/mids/.node/lib/node_modules/dapple/node_modules/merkle-patricia-tree/baseTrie.js:179:7
    at /Users/mids/.node/lib/node_modules/dapple/node_modules/merkle-patricia-tree/util.js:75:7
    at /Users/mids/.node/lib/node_modules/dapple/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
    at /Users/mids/.node/lib/node_modules/dapple/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:269:32
    at /Users/mids/.node/lib/node_modules/dapple/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
```

**Comment by mhhf** [comment]
This is the same bug as described here: https://github.com/nexusdev/dapple-test/issues/3
bottleneck is ethereumjs-vm which already resolved this. Once they publish their version I will update it immediately!

**Comment by mhhf** [comment]
Closing this as ethereumjs-vm got bumped to 2.0.1 and this issue should be resolved. Please reopen if problem still persists.
