### ISSUE TITLE
can not build contract and the errer 

### ISSUE THREAD

**Issue by pureland** [nexusdev/dapple#345]
Spanning multiple lines.
/Users/prue/.nvm/versions/node/v6.3.0/lib/node_modules/dapple/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nod

Error: Could not compile! Try navigating to /var/folders/mh/hy_z2t2d6kl7_2vbb1dmdr_m0000gn/T/dapple/7937570296012197 and executing "solc  --combined-json abi,bin,bin-runtime,interface,opcodes,asm -o *.sol"
at Function.compile (/Users/prue/.nvm/versions/node/v6.3.0/lib/node_modules/dapple/lib/native_compiler.js:52:13)
at Function.buildSources (/Users/prue/.nvm/versions/node/v6.3.0/lib/node_modules/dapple/lib/build.js:108:29)
at DestprueableTransform._flush (/Users/prue/.nvm/versions/node/v6.3.0/lib/node_modules/dapple/lib/streams/build.js:20:28)
at DestprueableTransform.<anonymous> (/Users/prue/.nvm/versions/node/v6.3.0/lib/node_modules/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
at DestprueableTransform.g (events.js:286:16)
at emitNone (events.js:86:13)
at DestprueableTransform.emit (events.js:185:7)
at prefinish (/Users/prue/.nvm/versions/node/v6.3.0/lib/node_modules/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:465:12)
at finishMaybe (/Users/prue/.nvm/versions/node/v6.3.0/lib/node_modules/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:473:7)
at endWritable (/Users/prue/.nvm/versions/node/v6.3.0/lib/node_modules/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:485:3)

**Comment by mhhf** [comment]
This is mostly not a dapple problem but caused by an internal solidity error such as wrong linking during the compilation process. Try running `solc --version`. If this succeed, try to follow the error instructions: e.g. go to the folder `/var/folders/mh/hy_z2t2d6kl7_2vbb1dmdr_m0000gn/T/dapple/7937570296012197` and run `solc --combined-json abi,bin,bin-runtime,interface,opcodes,asm -o *.sol` to compile your sources. This should fail.

**Comment by ryepdx** [comment]
To be fair, though, users should never see stack traces like this. Whatever's happening here should probably be caught and a more friendly message displayed.

**Comment by mhhf** [comment]
Fair point. This error msg will be friendlier in a future release :) 👍
