### ISSUE TITLE
TypeError: async.mapValues is not a function on dapple test

### ISSUE THREAD

**Issue by SilentCicero** [nexusdev/dapple#352]
dappfile
```
version: 1.6.0
tags: ["weifund","contracts","solidity"]
layout:
  sol_sources: contracts
  build_dir: lib
dependencies: {}
ignore: []
name: weifund-contracts
```

```
node ./node_modules/dapple/cmd/main.js test
```

```
Testing...
/bin/sh: 1: solc: not found
No local solc found. Failing over to JS compiler...
/home/nick/github/weifund-contracts-new-latest/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileS

TypeError: async.mapValues is not a function
    at DestroyableTransform._transform (/home/nick/github/weifund-contracts-new-latest/node_modules/dapple-test/lib/linklibraries.js:19:13)
    at DestroyableTransform.Transform._read (/home/nick/github/weifund-contracts-new-latest/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/nick/github/weifund-contracts-new-latest/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/nick/github/weifund-contracts-new-latest/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/home/nick/github/weifund-contracts-new-latest/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/home/nick/github/weifund-contracts-new-latest/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at Stream.method [as write] (/home/nick/github/weifund-contracts-new-latest/node_modules/duplexer/index.js:47:39)
    at DestroyableTransform.ondata (/home/nick/github/weifund-contracts-new-latest/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
```

node version: 6.5.0
npm version: 3.10.3

**Comment by tueric** [comment]
Need to `npm install async`

**Comment by mhhf** [comment]
Unfortunately this was missed during refactoring and is fixed in the current release. Thanks for reporting!
