### ISSUE TITLE
Cannot install Dapple on a fresh Lubuntu image

### ISSUE THREAD

**Issue by ryepdx** [nexusdev/dapple#353]
Pulled a fresh copy of Dapple from Github in my dev Docker in order to help Andy with the issues he was having with his tutorial build. Couldn't get it to install: kept getting warnings about missing dependencies. Rather than continue playing "whack-a-mole," I spun up a fresh Lubuntu machine in VirtualBox and tried to install from Github. I got:

```
ryepdx@ryepdx-VirtualBox:~/dapple$ dapple --version
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
module.js:471
    throw err;
    ^

Error: Cannot find module './build/Release/scrypt'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/dapple/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Tried installing secp256k1, tried installing the published package, no luck. Same error message every time.

Running NodeJS 6.9.1.

**Comment by mhhf** [comment]
tried it myself with lubuntu 16.10 in virtual box and had no problems with node 7 and npm 3.10.8
I had problems with secp256k1 a half year ago on DO instance. The problem was not enough ram and no swap space. Also: can you verify if gcc is installed?

**Comment by mhhf** [comment]
Btw, Andy's issue is resolved. He forgot to include the `--subpackages` flag during `dapple build`
