### ISSUE TITLE
When executing script with --no-simulation got 'Intrinsic gas too low'

### ISSUE THREAD

**Issue by rudolfix** [nexusdev/dapple#358]
I execute following script against CUSTOM environment (geth with custom genesis block)
```
pragma solidity >=0.4.0;

import "dapple/script.sol";
import "./ballot.sol";

contract BallotDeployScript is Script {
  event customEvent(uint value);

  function BallotDeployScript () {    
    Ballot ballot = new Ballot(1);

    // export token to the local environment
    exportObject("myballot", ballot);

    // static function call
    uint total = ballot.winningProposal();

    // log the found totalSupply
    customEvent(total);
  }
}
```
following command executes correctly both on simulated env. and on geth. I can see transactions being mined in the log:
dapple script run BallotDeployScript

However adding --no-simulation produces following error

```
dapple script run BallotDeployScript --no-simulation

sending transaction
/usr/lib/node_modules/dapple/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if

Error: Intrinsic gas too low
    at Object.InvalidResponse (/usr/lib/node_modules/dapple/node_modules/web3/lib/web3/errors.js:35:16)
    at /usr/lib/node_modules/dapple/node_modules/web3/lib/web3/requestmanager.js:86:36
    at request.onreadystatechange (/usr/lib/node_modules/dapple/node_modules/web3/lib/web3/httpprovider.js:114:13)
    at dispatchEvent (/usr/lib/node_modules/dapple/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/usr/lib/node_modules/dapple/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/dapple/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
```
Any idea what is wrong here?

**Comment by mhhf** [comment]
Hmm, which version on geth and OS are you using?
Just tested it on OS X 10.11.6, geth 1.4.18 with custom chain and dapple 0.8.28 and executing script with no-simulation flag and it works fine here.
Also is your project private or do you have some code for me which may reproduce this error?

**Comment by rudolfix** [comment]
I'm using geth 1.4.18 and dapple 0.8.28 on ubuntu. Different gas limit is used when I add --no-simulation flag. Without a flag:
	From:     765e57936915791dd13d59106204642d8f4cb2bc
	To:       [contract creation]
	Nonce:    19
	GasPrice: 20000000000
	GasLimit  **550399**

With a flag:
        To:       [contract creation]
	Nonce:    21
	GasPrice: 20000000000
	GasLimit  **90000**

which is fairly small. currently I'm evaluating your framework and I have no real code. here is the contract I'm deploying
https://gist.github.com/chriseth/618560d3f740204d46a5
